---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.configmapname.appsettings" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  appsettings.Kubernetes.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "CorsPolicyName": "AllowSpecificOrigin",
      "AllowedCrossDomains": [
        "http://{{- .Values.global.hosts.web -}}",
        "https://{{- .Values.global.hosts.web -}}"
      ],
      "Customize": {
        "Theme": "{{ .Values.appConfig.theme }}"
      }
    }
