apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-port
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https-port
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
